spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products
    password: $3cR3Tp4$$0Rd
    username: products_app
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true